language: c
sudo: required
dist: trusty
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake libapr1 libapr1-dev -y
  - bash .travis-install-cmocka.sh

script: ./bootstrap && ./configure && make && make check
